### ISSUE TITLE
help with frontail openhab inside docker

### ISSUE THREAD

**Issue by kevinshane** [mthenw/frontail#101]
hi guys, pretty noob here,
I start to learn docker and successfully running frontail and openhab2 in docker with 2 containers, however i don't know how to monitor openhab2,
`docker run --name=frontail --restart=always --net=host -tid -v /opt/openhab/userdata/logs:/log mthenw/frontail`
looks nothing and can't visit the web, what's the correct way to monitor the openhab2 log(docker) with a frontail docker? Please help me, thanks
Shane

**Comment by mthenw** [comment]
Hey @kevinshane 

I'm not sure how openhab2 works but in your example, you also need to expose ports from the container to the outside world. You can do that with either `-p` or `-P` CLI Docker param. Here is more info https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p-expose.
