### ISSUE TITLE
what to do for an auto reconnect

### ISSUE THREAD

**Issue by yveshanoulle** [mthenw/frontail#104]
I have a question more then an issue (might turn into an issue depending on where the answer goes)

I want to install frontail on a seperate raspberry pi. I want to use it to visualize the log from openhab (The application is not really important)

I would like when the openHab server reboots, that  frontail reconnect automa(t/g)ically. What should I do for that?

**Comment by mthenw** [comment]
Hey, assuming that frontail is accessible always on the same URL the reconnection should happen automatically. No additional steps needed.

Is it not working right now?

**Comment by yveshanoulle** [comment]
I was asking before I did an installation, because that was crucial for me to use it.
(and it was not documented)
