### ISSUE TITLE
Node 8 - Change daemon dependency by daemonize-process

### ISSUE THREAD

**Issue by rafaelquines** [mthenw/frontail#110]
Hello.

I'm using frontail in a raspberry. After I upgrade packages, frontail has a error when running with node 8. This bug is on daemon dependency, that is abandoned.

Was created a new package called daemonize-process that works very good.

Can you change this dependency? Or can I create a pull request with this change?

Thanks

**Comment by mthenw** [comment]
Hey,

according to the [README]https://github.com/silverwind/daemonize-process) this package works only for >=8 so right now it's not possible to switch that dependency. 

Can you paste the exact error message that you get?

**Comment by rafaelquines** [comment]
Thanks. Ok, sorry, I didn't see it before..

Follow the error:

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:380:11)
    at Object.exports.spawn (child_process.js:465:38)
    at Function.module.exports.daemon (/www/node-bb/node_modules/daemon/index.js:50:31)
    at module.exports (/www/node-bb/node_modules/daemon/index.js:25:20)
    at /www/node-bb/loader.js:223:21
    at FSReqWrap.oncomplete (fs.js:135:15)

This error was identified by this issue: https://github.com/indexzero/daemon.node/issues/41

Already exists a PR on daemon project: https://github.com/indexzero/daemon.node/pull/42

But I think this project is abandoned.

In frontail package.json, your dependency appoint to "github:zipang/daemon.node#48d0977c26fb3a6a44ae99aae3471b9d5a761085", but npm install command in my application can't donwload from this, by some reason.

➜  ~ sudo npm i -g frontail
npm WARN deprecated connect@2.11.0: connect 2.x series is deprecated
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/zipang/daemon.node.git /home/rafaelquines/.npm/_cacache/tmp/git-clone-9e39777e
npm ERR! /home/rafaelquines/.npm/_cacache/tmp/git-clone-9e39777e/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rafaelquines/.npm/_logs/2018-02-05T12_41_13_007Z-debug.log

Node: 8.9.4
NPM: 5.6.0

Can you help me? Or this problem isn't about your frontail app?

**Comment by mthenw** [comment]
Yeah, the issue is that `npm install` uses git underneath but because of some reason it doesn't work for you. 

I created a fork that fixes the issue and I also plan to publish it to npm so there will be no need to raw git dependency.

Tomorrow I will update the dep and publish new frontail version.

**Comment by rafaelquines** [comment]
Thank you @mthenw by your help.
And congratulation by your frontail app.

**Comment by rafaelquines** [comment]
It's checked. Now it's working perfectly. Thanks again.
