### ISSUE TITLE
Steaming Pretty formatted Log from Bunyan json file

### ISSUE THREAD

**Issue by jpkbeddu** [mthenw/frontail#117]
I am using Bunyan to log to a file which is in json format and logs like below

`
{"name":"myapp","hostname":"banana.local","pid":40161,"level":30,"msg":"hi","time":"2013-01-04T18:46:23.851Z","v":0}
{"name":"myapp","hostname":"banana.local","pid":40161,"level":40,"lang":"fr","msg":"au revoir","time":"2013-01-04T18:46:23.853Z","v":0}
`

And this json file can be viewed pretty using bunyan CLI.

Is it possible to stream the output of bunyan CLI to frontail instead of log file path ?

**Comment by mthenw** [comment]
Yes, there is. You can pipe anything through frontail, just use following command:

```
<some other command producing output> | frontail -
```
