### ISSUE TITLE
number of lines 

### ISSUE THREAD

**Issue by iahmad-khan** [mthenw/frontail#122]
hi

with each browser refresh the number of lines are just 10 , no matter even if i set -l option to 5000. 

am i doing anything wrong?

I want the number of lines to be at least 100 , like tail -n 100

**Comment by mthenw** [comment]
Hey,

can you confirm that the issue still occurs?

**Comment by mthenw** [comment]
I tried to repro that issue without a success. Let me know if this is an issue for you. Closing for now.
