### ISSUE TITLE
Constant Browser Refresh?

### ISSUE THREAD

**Issue by joshjung** [mthenw/frontail#124]
I have frontail running with a very default setup. However, it appears that every second or so the log file is reloaded in its entirety and copied to the browser output. So I end up with the log file repeating itself over and over in the browser.

Is this expected behavior? Shouldn't the script reload be able to identify which lines are new and which are not?

**Comment by joshjung** [comment]
I've confirmed this has something to do with my nginx setup. When I hit the port directly, rather than on my subdomain, the issue goes away.

**Comment by bbbf0621** [comment]
i'm having the same problem, how exactly did you solve this by hitting the port directly?
