### ISSUE TITLE
Add button to stop/restart watch

### ISSUE THREAD

**Issue by webjoel** [mthenw/frontail#137]
The lib ~~node-tail~~ tail enables to start/stop watch:

```
tail.watch();

tail.unwatch();
```

It's very good for many logs in little time when necessary analyse the log, so watch stop and after, start watch again.

It would be interesting to add this feature in this project as well.

I have an application that generates many logs.

**Comment by mthenw** [comment]
Hey @webjoel 

are you referring to https://www.npmjs.com/package/node-tail?

**Comment by webjoel** [comment]
@mthenw Yeap!

Suggestion:

1 - Use this lib I quoted;
2 - Create the similar feature in this project;

**Comment by mthenw** [comment]
I've been thinking about switching to this library (which also means supporting Windows OS) but there is no way to set an initial number of lines. Not sure how it will perform. I need to test it.

**Comment by webjoel** [comment]
I understand, meanwhile, in the current implementation, is it possible to add this stop and continue feature?

**Comment by mthenw** [comment]
Technically it's possible, but I'm probably not able to spend time on that. Are you interested in contributing?

**Comment by webjoel** [comment]
Okay, I'll try to develop.
