### ISSUE TITLE
Nginx works with frontail on http but not on https

### ISSUE THREAD

**Issue by hamwong** [mthenw/frontail#143]
Nginx works with frontail on http but not on https, as browser will report "too many redirect eroor" when  Nginx connect to frontail https, frontail https without ngix also fine, can this be fixed?

**Comment by mthenw** [comment]
Can you paste your nginx configuration?

**Comment by hamwong** [comment]
below code only changed server name and SSL location, SSL is register by letsencrypt

`worker_processes  1;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;


    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        listen [::]:80;
        server_name  www.XXYYZZ.com;


        return 301                      https://$server_name$request_uri;


        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    }
server {
    listen                          443 ssl;
    server_name                     www.XXYYZZ.com;

    ssl_certificate                 /etc/ssl/openhab.crt; 
    ssl_certificate_key             /etc/ssl/openhab.key; 
    add_header                      Strict-Transport-Security "max-age=31536000"; # Remove if using self-signed and are having trouble.

    location / {
        proxy_pass                            http://192.168.1.2:8080;
        proxy_set_header Host                 $http_host;
        proxy_set_header X-Real-IP            $remote_addr;
        proxy_set_header X-Forwarded-For      $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto    $scheme;
        satisfy                               any;
        allow                                 192.168.1.1/24;
        allow                                 127.0.0.1;
        deny                                  all;
        auth_basic                            "Username and Password Required";
        auth_basic_user_file                  /etc/nginx/.htpasswd;
    }

    location /grafana/ {
        proxy_pass http://192.168.1.2:3000/;
    }
    location /frontail/ {
        proxy_pass https://192.168.1.2:9001/frontail;
    }
}`

**Comment by pacive** [comment]
I had the same problem, the solution was to use 
`location /frontail {`
instead of
`location /frontail/ {`

I however, have a different issue using https. I get an error in chrome:
```
Refused to execute script from 'https://<address>/frontail/socket.io/socket.io.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```
What's strange is that the `Content-type`-header is set to `application/javascript` when loading over http, but `text/html` when loading over https. I believe this error is because of nginx though..

**Comment by hamwong** [comment]
> 
> 
> I had the same problem, the solution was to use
> `location /frontail {`
> instead of
> `location /frontail/ {`
> 
> I however, have a different issue using https. I get an error in chrome:
> 
> ```
> Refused to execute script from 'https://<address>/frontail/socket.io/socket.io.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
> ```
> 
> What's strange is that the `Content-type`-header is set to `application/javascript` when loading over http, but `text/html` when loading over https. I believe this error is because of nginx though..
> 
> Edit:
> This was also because of a `/` too much: using
> 
> ```
> proxy_pass    http://<address>/frontail;
> ```
> 
> instad of
> 
> ```
> proxy_pass    http://<address>/frontail/;
> ```
> 
> solved it!

Thank you @pacive, it works!! unblievable.

**Comment by mthenw** [comment]
Thanks @pacive for the help.
