### ISSUE TITLE
Possible to mount in an existing Express app?

### ISSUE THREAD

**Issue by marclar** [mthenw/frontail#147]
I was thinking of including this in my project but mounting it as middleware, e.g.

```
const app = express();
const frontail = require('frontail');

app.get('/', (req, res) => {res.send('Hello World!')});

app.use('/logs', frontail);

```

Can frontail be used in this way?

**Comment by mthenw** [comment]
Hey, it's not possible with the current architecture. One option that could help could be just running express js server and piping output to frontail:

`node server.js | frontail -`

**Comment by marclar** [comment]
Thanks for the response, @mthenw. I was also thinking of starting frontail using `child_process.execFile` and then proxying requests from a route on my primary app to the frontail server/port.
