### ISSUE TITLE
Memory leaks in browser client code?

### ISSUE THREAD

**Issue by wowcut** [mthenw/frontail#148]
Hi, I am a little bit concerned about
https://github.com/mthenw/frontail/blob/90d1428449fbecb6e41dbb77990821e6edc6f2d9/web/assets/app.js#L305 
because of
https://github.com/mthenw/frontail/blob/90d1428449fbecb6e41dbb77990821e6edc6f2d9/web/assets/app.js#L46

If I understand that code right, it will never remove elements and add a never ending stream of log lines to the dom plus one event listener for each line, as the condition to remove the element is never true. 

I hope I am wrong? I really need a tiny browser-log-browser, log.io is dead and ELK stack is too much for a few quick logs, so I am very happy that you are working on this and this project seems to be active. However, browser tabs with logfiles tend to be open a very long time, so memory optimization is crucial. 

Have you considered using a [grid](https://github.com/6pac/SlickGrid/wiki)?

**Comment by wowcut** [comment]
Here are some more interesting grid insights: https://stackoverflow.com/questions/45910217/js-grid-performance-comparison

**Comment by wowcut** [comment]
I tend to give https://clusterize.js.org/ a try, looks very interesting and might be the right choice for log data. What do you think?

**Comment by mthenw** [comment]
Hey @wowcut,

`_linesLimit` is set in https://github.com/mthenw/frontail/blob/master/web/assets/app.js#L258 based on the value sent from the backend. You can manipulate that variable with `-l, --lines` CLI param. The default value is 2000. Assuming that you won't set it to some very big number it should probably be fine.
