### ISSUE TITLE
Multiple files do not show after refresh

### ISSUE THREAD

**Issue by robguinness** [mthenw/frontail#150]
I've noticed that when serving multiple files, only one file is displayed after a browser refresh.

# Steps to reproduce:

1. `$ frontail -n 30 --url-path /frontail /var/log/nginx/access.log /var/log/nginx/error.log`
2. View in browser
3. Refresh the browser

# Expected behavior
- Both log files should still be visible.

# Actual behavior
- Only the first log file is visible.

**Comment by mthenw** [comment]
Hey, @robguinness

which version do you run?

**Comment by robguinness** [comment]
Sorry for the delayed response. v4.4.0

**Comment by mthenw** [comment]
@robguinness can you try with the new version?

**Comment by jmahmens** [comment]
Hi, I'm using frontail with openhab to shoe the logs.
With frontail 4.5.3 only the last given log is shown.
frontail.service:
`ExecStart=/usr/bin/frontail --ui-highlight --ui-higlight-preset /usr/lib/node_modules/frontail/preset/openhab.json -t openhab -l 6000 -n 600 /var/log/openhab2/events.log /var/log/openhab2/openhab.log
`
Swaping event.log and openhab.log and reload/restart service shows the other.
Highlighting with some other then default or dark wont work.

**Comment by mthenw** [comment]
@jmahmens thanks for reporting. Can you open the new issue with your problem?
