### ISSUE TITLE
Only the last element of the words list in json preset is processed.

### ISSUE THREAD

**Issue by pitonmd** [mthenw/frontail#151]
I found an error in the _highlightWord() function in web /assets/app.js, which caused only the last object in the _highlightConfig.words list to be processed.

To fix, you need to replace line 180 in /assets/app.js:
`output = line.replace(`
with
`output = output.replace(`

**Comment by macfly92** [comment]
Hello, I have the same issue.
Will it be fixed in the next builded version ?
Thanks you.
