### ISSUE TITLE
"Pkg: Error reading from file"

### ISSUE THREAD

**Issue by tamasgal** [mthenw/frontail#158]
I am using `frontail` to monitor the log files coming from the DAQ system of a neutrino detector. We're very glad to have this tiny tool, thanks!

The DAQ system runs on CentOS and I decided to get the self-contained binary, however sometimes when I start `frontail`, I get the error:

    Pkg: Error reading from file.

And the whole package seems to be broken. I then have to download it again (in fact I keep a backup copy and overwrite it regularly as a workaround).

This is probably caused due to the fact that when I run `frontail` with the `--disable-usage-stats`, I cannot quit it by pressing the `CTRL+C` keys, but I have to kill it using `kill -9 PID`. I guess some files might get corrupted due to this hard shutdown.

**Comment by mthenw** [comment]
Hey @tamasgal,

thanks for creating the issue. I will take a look.

**Comment by mthenw** [comment]
I released new version v.4.5.4. Please confirm that it works now.

**Comment by tamasgal** [comment]
Unfortunately it's not working. When the process is killed, the app image is broken:


```
> frontail logs/.log –ui-highlight –ui-highlight-preset frontail.json –theme dark -l 10000 -n 200 -p 8082
Pkg: Error reading from file.
```

**Comment by mthenw** [comment]
@tamasgal which OS do you run?

**Comment by tamasgal** [comment]
CentOS 7. It happens when the process is killed... 🤔

**Comment by tamasgal** [comment]
Unfortunately we are still fighting with this issue, even after the latest update on signal handling.

Sometimes the package is corrupted after killing it but now it reports this:

```
RangeError: Invalid array length
    at new CBuffer (/snapshot/frontail/node_modules/CBuffer/cbuffer.js:25:15)
    at new Tail (/snapshot/frontail/lib/tail.js:17:18)
    at module.exports (/snapshot/frontail/lib/tail.js:58:37)
    at Object.<anonymous> (/snapshot/frontail/index.js:123:18)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
```

**Comment by mthenw** [comment]
Have the issue changes you reported it in January? I mean are you able to quit frontail with `CTRL+C`? As I understand the issue is that when you kill the process with `kill -9` the next time you try to run it you get an error "Pkg: Error reading from file."?

**Comment by tamasgal** [comment]
We are currently evaluating it since it might be that someone copied over an old backup file (which we used in a cronjob to repair it). I'll report back!

FYI: Two days ago I changed to `supervisord` and now we are managing also the `frontail` application with that. It sends `SIGTERM`, before the process was inside a `tmux` session and when it got killed the package has been damaged.

**Comment by mthenw** [comment]
@tamasgal any update?

**Comment by tamasgal** [comment]
Seems to work so far! I will close this...
