### ISSUE TITLE
Not shutting down via signals if usage reporting is disabled

### ISSUE THREAD

**Issue by apeteri** [mthenw/frontail#160]
Hi Maciej,

I am using release 4.5.3 with a systemd service script, and I have noticed that the service waits for the whole ~90 second grace period when stopping, before it gets killed forcefully. Systemd attempts to stop a service by sending `SIGTERM` to its process group by default.

It seems that the callback for usage stats reporting in `stats.js` is not invoked if no `tracker` instance exists: https://github.com/mthenw/frontail/blob/205cdbf6961d556e0822d70677e71226adc5dc32/lib/stats.js#L57-L63

Due to this, signals have no effect at the end of `index.js`: https://github.com/mthenw/frontail/blob/205cdbf6961d556e0822d70677e71226adc5dc32/index.js#L159-L165

Regards,
András

**Comment by apeteri** [comment]
Possible duplicate of #158.

**Comment by mthenw** [comment]
Thanks for reporting. I will take a look.

**Comment by mthenw** [comment]
I released new version v.4.5.4. Please confirm that it works now.

**Comment by apeteri** [comment]
Looks good, now the process stops immediately. Thanks! 😃
