### ISSUE TITLE
How I can use as logrotate

### ISSUE THREAD

**Issue by prasenforu** [mthenw/frontail#171]
Along with how I can take advantage of logrotate?

**Comment by mthenw** [comment]
Hey, can you be more specific what exactly you want to achieve?

**Comment by prasenforu** [comment]
Sorry !! delay in reply..

in README file you mentioned that as features "log rotation"

![image](https://user-images.githubusercontent.com/19322497/61942422-01779180-afb7-11e9-895c-d6be4e3a80ea.png)

Can I use logrotate that I am using for tail.

**Comment by mthenw** [comment]
Yes, definitely. It should work.

**Comment by timdonovanuk** [comment]
Right...but how? :) How does one set up this to rotate logs?
