### ISSUE TITLE
Show Empty Lines

### ISSUE THREAD

**Issue by nayrnet** [mthenw/frontail#172]
Output of my software uses carriage returns to demarc data in the stream.. 

I accomplished this with a simple hack, modify tail.js to include an option for byline:
```byline(process.stdin,{ keepEmptyLines: true }).on```

Perhaps this should be configurable from a runtime option.
demo @ https://igate.nayr.net/direwolf/

**Comment by mthenw** [comment]
Hey, can you create a PR for that?

**Comment by nayrnet** [comment]
is that not what this is? I took the feature part off if you think its a bug.

**Comment by nayrnet** [comment]
done
