### ISSUE TITLE
How to start automaticly ?

### ISSUE THREAD

**Issue by gamersalpha** [mthenw/frontail#207]
Hello ok now that's work, but i have to say online my terminal :
but if i close i lost him, so how to start with the apps with the systeme : 

and how to add 2 log files in the same times

thanks

**Comment by dalmosantos** [comment]
Running a binary file in background process: `nohup ./frontail /log/syslog &`
About tailing [multiple files] (https://github.com/dalmosantos/frontail/blob/master/README.md#tailing-multiple-files).
