### ISSUE TITLE
HTTPS on IOS

### ISSUE THREAD

**Issue by Marco1097** [mthenw/frontail#208]
On IOS when HTTPS in enable, the page load correctly, but logs are not shown.

**Comment by Marco1097** [comment]
Some info
Frontail Docker version latest (the one from 6 days ago)
IOS 13.4.1

**Comment by RafaelMiquelino** [comment]
Hi, I have the same issue on Safari, MacOS Catalina. It works well when accessing the ip address directly but the logs are not shown when accessing through the reverse Proxy (Traefik). It works as expected when using Chrome.

Please, see screenshots below: 

Access through the ip-adress:port (works fine):
<img width="1022" alt="Screen Shot 2020-05-01 at 19 56 17" src="https://user-images.githubusercontent.com/31367475/80847496-4d123800-8be6-11ea-9989-982000e33a35.png">

Access through the host address (doesn't work):
<img width="1024" alt="Screen Shot 2020-05-01 at 19 55 20" src="https://user-images.githubusercontent.com/31367475/80847506-54394600-8be6-11ea-8ea3-7ff8dc51cdf6.png">

**Comment by Marco1097** [comment]
@RafaelMiquelino have you tried using integrated https instead of a reverse proxy?
I also have the problem with the reverse proxy (Nginx), but it also appear when using this option
```
  -k, --key <key.pem>           Private Key for HTTPS, option works only along with -c option
  -c, --certificate <cert.pem>  Certificate for HTTPS, option works only along with -k option
```

**Comment by RafaelMiquelino** [comment]
> @RafaelMiquelino have you tried using integrated https instead of a reverse proxy?
> I also have the problem with the reverse proxy (Nginx), but it also appear when using this option
> 
> ```
>   -k, --key <key.pem>           Private Key for HTTPS, option works only along with -c option
>   -c, --certificate <cert.pem>  Certificate for HTTPS, option works only along with -k option
> ```

What exactly do you mean with integrated https? I'm using Let's encrypt certificate with the issue and renewal automatically done by Traefik.

I collected a bit more information on the error, please see below the error indicated on the browser console:
```
[Error] WebSocket connection to 'wss://log.pincar.com.br/socket.io/?EIO=3&transport=websocket' failed: Unexpected response code: 401 (x26)
```
Do you have any indication on how to solve this issue?

**Comment by Marco1097** [comment]
> What exactly do you mean with integrated https? I'm using Let's encrypt certificate with the issue and renewal automatically done by Traefik.

I mean that frontail can support https without a reverse proxy.

Why am I talking about https? Because I think the problem is caused by that. In the first case you log in with the ip, while in the second case with the hostname, however in the second case there is an https connection

**Comment by RafaelMiquelino** [comment]
> Why am I talking about https? Because I think the problem is caused by that. In the first case you log in with the ip, while in the second case with the hostname, however in the second case there is an https connection

Yes, I got it and I think that makes sense. But I want to solve this using my reverse proxy solution for the sake of simplicity and standardisation with the other services I'm running on the same server. I'll check deeper the issue and how to solve it and will post back if I find any solution.
