### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by opensauce17** [mthenw/frontail#25]
Hi,

This is a great solution and I would really like it to work. I am more than likely making a 101 error so please excuse my ignorance. When I start up as a daemon this is my PID info : 

/usr/bin/node /usr/lib/node_modules/frontail/index.js -p 9001 -n 10 -l 2000 -t default /var/log/messages

But when I go to the server on port 9001 I pretty much get a blank page and do not see the log file specified.

Could you please let me know what I am missing.

Thanks

**Comment by vickyrare** [comment]
One can make frontail to work on windows by using tail.exe provided by MKSNT. Download it from following link.

http://www.filedropper.com/tail

You need tail.exe in your path. You also need to make change to /lib/tail.js

change -F to -f
var tail = spawn('tail', ['-n', options.buffer, '-f', path]);

**Comment by mthenw** [comment]
@vickyrare I'm planning to change internal implementation to not use `tail` command but currently I don't have time for that. I've created #38.
