### ISSUE TITLE
Frontail a directory

### ISSUE THREAD

**Issue by tommedema** [mthenw/frontail#26]
Great little project this is.

I'd like to use this for a rotating log system I have. Unfortunately the file names keep changes due to the rotating nature of the system. Therefore it would be useful if I could specify a folder to monitor, and then when I visit the site it would show me all available files within this folder.

**Comment by emilsoman** [comment]
@mthenw Is this still the current behavior? Asking because when I run frontail with a directory,

    frontail /var/log
I get the following error: 
```
tail: error reading ‘/var/log’: Is a directory
tail: /var/log: cannot follow end of this type of file; giving up on this name
```

**Comment by mthenw** [comment]
@emilsoman I think so, but you have to put * at the end. So `frontail /var/log/*` should work.

**Comment by emilsoman** [comment]
@mthenw that works. Thanks!

**Comment by mnsrulz** [comment]
@mthenw while I am trying to fontail a directory as 

`frontail .vscode/logs/log*.txt`
or 
`frontail .vscode/logs/*`

it gives me below error in the windows os


```
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\.vscode\logs\log*.txt'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\.vscode\\logs\\log*.txt'
}
```

at the same time if I just tail a single file it runs fine
`frontail .vscode/logs/log.txt`

Is there something you can advise on this?
