### ISSUE TITLE
SSH + daemonize not working

### ISSUE THREAD

**Issue by mdelapenya** [mthenw/frontail#41]
Hi, first of all, thanks for this really cool tool! It is exactly what I need to share some server logs.

For that, I tried the SSH configuration with daemonize enabled, but it does not work for me, it's always using the false branch on tail.js (local execution).

This is the command I execute:

```shell
frontail --remote-host REMOTE_IP --remote-user REMOTE_USER -p 7777 -n 50  --ui-highlight default.json -d --log-path /tmp/frontail.log REMOTE_PATH_TO_MY_LOG
```
Adding this trace:
```
console.log("SSH OPTIONS: " + program.remoteHost + " - " + program.remoteUser + " - " + program.remotePort);
```
it returns "SSH OPTIONS: null - root - 22", although I passed the variables

On the other hand, removing the daemonize commands, it works as expected.

I believe that the sshOptions variable is not set when daemonizing the program. I'd try to fix it by myself, but I'm not a node expert :S 

Thanks!

**Comment by mthenw** [comment]
Hi @mdelapenya, 
I was on vacation during previous week. I will look at it later today.

**Comment by mdelapenya** [comment]
Thanks @mthenw! I sent you a pull with test too #42

**Comment by mthenw** [comment]
@mdelapenya published v.1.4.1 (b85c828)
