### ISSUE TITLE
ui-highlight not working - two scenarios

### ISSUE THREAD

**Issue by mv5492** [mthenw/frontail#44]
1. I think the daemonize option creates a conflict with --ui-highlight

<path>/local/bin/frontail --host development.web.com --port 8181 --pid-path '<path>/pub/node/frontail.8181.pid' --key '<path>/local/ssl/certs/new_dev_private.key' --certificate '<path>/local/ssl/certs/upstartdev.crt' --log-path <path>/pub/node/frontail.log  --daemonize --ui-highlight <path>/local/lib/node_modules/frontail/preset/default.json /tmp/front1

The server starts but --ui-highlight does not work. If I remove --daemonize or -d the --ui-highlight works fine as specified above with full path to json file

2. If I leave off the [path] to --ui-highlights (as shown) I get the error below

<path>/local/bin/frontail --host development.web.com --port 8181 --pid-path '<path>/pub/node/frontail.8181.pid' --key '<path>/local/ssl/certs/dev_private.key' --certificate '<path>/local/ssl/certs/dev.crt' --log-path <path>/pub/node/frontail.log --ui-highlight /tmp/front1

Arguments needed, use --help

If I leave off --ui-highlight all together there is no highlighting - not picking up defaults. The daemonize option is not specified.

My --ui-highlight input file works:
{
    "words": {
        "err": "color: red;"
    },
    "lines": {
        "err": "font-weight: bold; background-color: yellow;"
    }
} 

3. I modified index.js and specified the full path to the default json file and started the server as follows - moved the --ui-highlight switch to the middle of the command. This works (but still does not work with --daemonize). This make --ui-highlight positional, at least it can't be the last switch:

<path>/local/bin/frontail --host development.web.com --ui-highlight --port 8181 --pid-path '<path>/pub/node/frontail.8181.pid' --key '<path>/local/ssl/certs/dev_private.key' --certificate '<path>/local/ssl/certs/dev.crt' --log-path <path>/pub/node/frontail.log  /tmp/front1

Thank you for looking. Mike

**Comment by mthenw** [comment]
Hi,

thanks for reporting. Both cases were fixed in 2.0.0. I've also introduced new option `--ui-highlight-preset` for providing highlight preset path.

**Comment by mv5492** [comment]
My pleasure. I really like your approach to tail -f to a browser. I'm looking forward to issue#38
