### ISSUE TITLE
Docker image for frontail

### ISSUE THREAD

**Issue by faizhasim** [mthenw/frontail#45]
Hi

We are using your project to tail some logs for our development purposes, involving Docker-based containerization.

We just want to let you guys know that we have created a [public Docker image](https://registry.hub.docker.com/u/servicerocket/docker-fronttail/) on Docker hub if anyone else is planning to use it.

**Comment by mthenw** [comment]
Hi @faizhasim, 

that's super cool. But could you rename docker image on docker hub to "frontail" (on t) as it's correct name?

**Comment by faizhasim** [comment]
Yea, I just noticed on the name. I'm a little bit occupied now, will track that from our side and we'll do a new release instead. I think I can't rename once it's published, but I could be wrong.

**Comment by mthenw** [comment]
Thanks.

You can remove and push new image to registry.

**Comment by faizhasim** [comment]
Sorry for very long update. I've created https://registry.hub.docker.com/u/servicerocket/docker-frontail/.

I will delete the old one later.

**Comment by mthenw** [comment]
@faizhasim great, thanks! I will add info to README.
