### ISSUE TITLE
Select file to tail from frontend?

### ISSUE THREAD

**Issue by jamesmr89** [mthenw/frontail#48]
Would it be possible to change the file being watched from the front end?

IE I have a drive with hundreds of logfiles that are constantly being written to and new ones created constantly.  I'd like to be able to feed an argument when landing on frontail page to select the file to be tailed:

http://localhost:9001/mydir/myfile.log

Would that be possible, without spawning a new instance of frontail for each file to be watched?

Thanks,
james

**Comment by mikeatlas** [comment]
:+1:  nice idea

**Comment by matteocontrini** [comment]
Definitely :+1: on this

**Comment by mikeatlas** [comment]
You'd probably want some kind of wildcard/regex option on the startup menu

**Comment by jamesmr89** [comment]
@mikeatlas 

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png) on the whitelist regex idea.

**Comment by mthenw** [comment]
Looks like the most requested feature, haha. I will be off for next two weeks but after that I will try to do something with that.

Still, thanks for reminding.

**Comment by codeskyblue** [comment]
really want it.

**Comment by jamesmr89** [comment]
Hi @mthenw, just wanted to see if you had any idea on a time frame on this?

Thanks,
~

**Comment by mthenw** [comment]
@jamesmr89 TBH, I completely don't have time right now to do that. Also, the truth is that I don't feel that this feature should be in frontail. It supposed to be very simple tool. With this feature it become to remote file explorer. Not sure if this is a common knowledge but you can use `*` in a file path e.g. `frontail /var/log/system*`.

I will leave this issue open for discussion but I'm not planning to implement this right now.

**Comment by matteocontrini** [comment]
You could add something about the `*` in the readme, at least

**Comment by mthenw** [comment]
@matteocontrini good point :) https://github.com/mthenw/frontail/commit/3df000920cfccb3b88923aba94e67b5c10d25950
