### ISSUE TITLE
README lists -h option as alias for both --help and --host

### ISSUE THREAD

**Issue by ChristianWilkie** [mthenw/frontail#53]
In the project README under Usage the option `-h` is listed as an alias for both `--help` and `--host`. When I run `frontail -h` it seems to actually refer to `--host`:

```
error: option `-h, --host <host>' argument missing
```

Also, running `frontail --help` lists the same thing:

```
Usage: frontail [options] [file ...]

Options:

-h, --help                    output usage information
...
-h, --host <host>             listening host, default 0.0.0.0
...
```

Anyway, not a huge deal, but I just thought I'd mention it.

**Comment by mthenw** [comment]
Thanks for reporting. It's not a big deal, but based on my quick research it won't be easy. I need to replace options parser (commander) with other library.

**Comment by Spown** [comment]
yeah... that, or just remove "-h" from "-h, --help  output usage information" both in the readme and the referance. so only "--help" would remain, duh

**Comment by mthenw** [comment]
@Spown wanna contribute? :)

**Comment by Spown** [comment]
well, I already forked it. right now I'm trying to compose a buildable version for node 4, since  socket.io 0.9 you are using is so old it won't even compile. and the node-temp in tests doesn't work either.

**Comment by mthenw** [comment]
Yeah, there is a bunch of other stuff that doesn't work on Node 4. I will try to fix that today, so you can work only on this fix.

**Comment by mthenw** [comment]
@Spown push to master version working with Node v4. There is no problem with socket.io (TravisCI can confirm).

**Comment by Spown** [comment]
funny thing, node-temp runs in node 4.2.2 under linux, but not in windows

https://travis-ci.org/Spown/frontail/jobs/127997186

```
  49 passing (889ms)
  3 failing

  1) tail calls event line if new line appear in file:
     Uncaught Error: spawn tail ENOENT
      at exports._errnoException (util.js:874:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
      at onErrorNT (internal/child_process.js:344:16)

  2) tail buffers lines on start:
     Uncaught Error: spawn tail ENOENT
      at exports._errnoException (util.js:874:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
      at onErrorNT (internal/child_process.js:344:16)

  3) tail buffers no lines on start by default:
     Uncaught Error: spawn tail ENOENT
      at exports._errnoException (util.js:874:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
      at onErrorNT (internal/child_process.js:344:16)
```

**Comment by Spown** [comment]
the thing is I really need to make it run in windows, because I need to watch for a remote file on an Openshift server (where I'm not able to run multiple apps on different ports, afaik). So if I unable - I kinda have no use for it...

**Comment by Spown** [comment]
it would be really cool, if this module had an express middleware version though

**Comment by mthenw** [comment]
There is newer version on `temp`. You could try using that.

**Comment by Spown** [comment]
yeah, I just found another trailing solution, sorry. still according to https://www.npmjs.com/package/commander#helpcb you don't need to replace options parser - just take one "-h" from the help text.
