### ISSUE TITLE
Getting "Failed to load resource: Could not connect to the server. http://localhost:9001/socket.io/1/?t=1447090642687"

### ISSUE THREAD

**Issue by atljeremy** [mthenw/frontail#54]
Getting `Failed to load resource: Could not connect to the server. http://localhost:9001/socket.io/1/?t=1447090642687` in the console log of the web interface.

I ran `$ npm install frontail -g`
and then `$ frontail output.log` (output.log does exist in the directory I was in)

I see the web UI in the browser. However, any updates to the log do not show up in the web UI automatically, as I was expecting them to. After looking at the console log in the browser, I saw the error referenced above.

Is there another setup step that isn't documented that I need to know?

**Comment by atljeremy** [comment]
Cancel that, I had killed the frontail process which resulted in those error messages. However, I still can't figure out how to get it to actually log new updates to the log file to the web interface automatically. Any ideas?

**Comment by atljeremy** [comment]
Sorry, must have been something I was doing wrong. it's working now though. Thanks for this!

**Comment by mthenw** [comment]
You're welcome :)
