### ISSUE TITLE
New feature to ignore some lines based on a pattern

### ISSUE THREAD

**Issue by profy12** [mthenw/frontail#55]
Hi,

A feature is missing for me : the ability to ignore some lines matching a pattern.

Just a proposition, this tools is already very awesome, thanks for your job.

Have a good day.

**Comment by mthenw** [comment]
Hey, thanks for your feedback. As a searchbox in frontail supports regexp expressions you can search for e.g. `^(?!.*someword).*`. Does it solve your problem?
