### ISSUE TITLE
How can I use frontail to display log file output in my own website/view?

### ISSUE THREAD

**Issue by atljeremy** [mthenw/frontail#56]
I have an existing website that I'd like to be able to show log file output in. Instead of linking to the frontail `index.html`, how can I configure frontail to work with my own website/view?

I started poking around and I copied over the `app.js` and `socket.io.js` into my own website, started the frontail service as a daemon, and tried launching my site. I get the following error in the console...

![rentpath_seo_tool](https://cloud.githubusercontent.com/assets/1019253/11062989/6ae1af5a-8781-11e5-9bee-21b0e9d10891.png)

For testing purposes I went into the `socket.io.js` and hardcoded all of the `port` options to 9001 and the error went away and no new errors showed up. However, I'm noticing the `__NAMESPACE__` placeholder isn't being set in my website. It does get set properly in the frontail index.html site. What sets this variable and how can I hook it up to my site?

**Comment by mthenw** [comment]
as you can see from frontail source you need to do only this
```
    <script src="/socket.io/socket.io.js"></script>
    <script src="/app.js"></script>
    <script type="text/javascript">
        var socket = new io.connect('/' + '7c56f6a00c02d5062e236550b16e6da3');

        window.load = App.init({
            socket: socket,
            container: document.getElementsByClassName('log')[0],
            filterInput: document.getElementsByClassName('query')[0]
        });
  </script>

```

**Comment by mthenw** [comment]
> However, I'm noticing the __NAMESPACE__ placeholder isn't being set in my website. It does get set properly in the frontail index.html site. What sets this variable and how can I hook it up to my site?

It's being before sending index.html to client here (https://github.com/mthenw/frontail/blob/master/index.js#L52). So without that you won't be able to get log entries. 

Maybe it would be easier to run frontail in a iframe?
