### ISSUE TITLE
Stop --daemonize

### ISSUE THREAD

**Issue by ajitam** [mthenw/frontail#57]
first of all - great script!

if I run frontail with -d param. How do I stop it?

**Comment by mthenw** [comment]
`$ kill` :)

**Comment by ajitam** [comment]
hmm I get 
```
$ kill :)
$ -bash: syntax error near unexpected token `)'
```

hehe just messing with you. That was my initial plan - to run it with
```
$ ... --pid-path ~/.frontail/daemon.pid
```

but the problem is that process make a 'sub process'
```
$ ps axjf

...


    1 10687 10687 10687 ?           -1 Ssl   1000   0:15 /usr/bin/nodejs /home/user/.npm-global/lib/node_modules/frontail/index.js -h 0.0.0.0 -p 8888 -n 1
10687 10692 10687 10687 ?           -1 S     1000   0:00  \_ tail -n 10 -F /home/user/log.log
```

and when I kill the first one (the one I have PID for), second  one (`tail ...`) remains :/

**Comment by mthenw** [comment]
Damn! Looks like https://github.com/mthenw/frontail/blob/master/lib/tail.js#L43 is not working. Thanks for reporting!

**Comment by ajitam** [comment]
For debug
```
node v0.10.35
Ubuntu 15.10
```

**Comment by mthenw** [comment]
v2.1.2 published to NPM :)

**Comment by ajitam** [comment]
well that was fast!

updated, tested, WORKS!

**Comment by zubair1024** [comment]
hey, I don't get it, is there an easy way to stop the daemon, I have multiple frontail processes running. How do I stop them all?

**Comment by ajitam** [comment]
One way is to create the scripts which starts all the demons in na loop

```
frontail [all the cmd] --pid-path ~/path/to/some/location/d1.pid
frontail [all the cmd] --pid-path ~/path/to/some/location/d2.pid
```

and then when you want to stop them you loop over `.pid`-s in `~/path/to/some/location/` and kill one by one
