### ISSUE TITLE
Behind a reverse proxy

### ISSUE THREAD

**Issue by kujiy** [mthenw/frontail#66]
Hi. Thank you for sharing your great project.

I'd like to use this behind a reverse proxy. But it seems to have a problem.

- Launch frontail with port 9001
- Access with port 80

Then the program works but image/css would be not found because they aren't in there.

![0406-02](https://cloud.githubusercontent.com/assets/6756543/14308459/450fb8e4-fc11-11e5-9416-881366220ce7.png)

Here are an example of setting of apache.
```
<VirtualHost *:80>
  ProxyPreserveHost On
  ProxyRequests Off
  ServerName hs.kc.jp
  ServerAlias example.com
  ServerName example.com
  ServerAlias example.com
  ProxyPass /frontail http://localhost:9001/
  ProxyPassReverse /frontail http://localhost:9001/
</VirtualHost>
```

I'm not sure how I could solve this.
Could you give me a hint? I want to send PR if I can(though I'm not a developer of npm...).

**Comment by mthenw** [comment]
Hi, thanks for reporting. The problem is that frontail's web app uses absolute paths for resources (starting with "/"). I guess that removing those slashes in https://github.com/mthenw/frontail/blob/master/lib/web/index.html should solve the problem.

Do you want to create PR for that?

**Comment by kujiy** [comment]
Oh, sorry I missed your answer. Okay I'll try it if I have time. Thank you.
