### ISSUE TITLE
filter out control chars

### ISSUE THREAD

**Issue by ORESoftware** [mthenw/frontail#72]
this is a pretty cool project, having some issues though

the tail command (using bash terminal) on Mac OSX seems to filter out (interpret) control chars

Is there an option to do so with frontail?

![screen shot 2016-06-14 at 1 37 58 pm](https://cloud.githubusercontent.com/assets/11139560/16058896/67dc7088-3235-11e6-9787-7ec23c6037b3.png)

**Comment by ORESoftware** [comment]
the red line at the top is via control chars, so not sure why that got interpreted correctly - it was a part of the first 10 lines from the original tail command if that's of any help

**Comment by ORESoftware** [comment]
also it doesn't appear that new line chars are being honored either, here is what iTerm2 looks like tailing the same file:

![screen shot 2016-06-14 at 1 41 35 pm](https://cloud.githubusercontent.com/assets/11139560/16058948/c09cd42e-3235-11e6-9909-8de608e0a2a9.png)

**Comment by mthenw** [comment]
Weird, lines are converted using https://github.com/drudru/ansi_up. Looks like something wrong here.

**Comment by ORESoftware** [comment]
I can probably prevent logging control chars upstream, but then I won't get any colors. Definitely would be great to have colors available in the browser. Let me know if you need more info.

**Comment by ORESoftware** [comment]
any luck investigating this? I haven't thought about it much but will let you know if I can think of a good reason why it may happen

**Comment by mthenw** [comment]
@ORESoftware haven't had enough time. I'm pretty busy these days :/

**Comment by ORESoftware** [comment]
word np

**Comment by mthenw** [comment]
Fixed in v3.1.2 :)

**Comment by ORESoftware** [comment]
cool will test it out thx!
