### ISSUE TITLE
proxy with nginx

### ISSUE THREAD

**Issue by kmcintyre** [mthenw/frontail#73]
Is it possible to proxy via nginx to a specific path - http://myserver/tail?  I can only seem to get working at root context.

An example would be great, if available.

**Comment by GeeWizWow** [comment]
Reverse proxy should do the trick, something along these lines?

`server {
    listen 80;

    server_name myserver.com;

    location /tail {
        proxy_pass http://localhost:9001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}`

Cheers, F

**Comment by mthenw** [comment]
Closing for now. @kmcintyre let me know if @GeeWizWow solution didn't help.

**Comment by kmcintyre** [comment]
I see that, but I realized the browser when served the lib/web/index.html file 'as is' still didn't work for me.

I editing the index.html changing link and script to /assets/

    <link rel="stylesheet" type="text/css" href="/assets/styles/__THEME__.css">

then copy - 
/usr/lib/node_modules/frontail/node_modules/socket.io/node_modules/socket.io-client/socket.io.js to 
/usr/lib/node_modules/frontail/lib/web/assets/socket.io/socket.io.js

Then finally nginx 

    location /socket.io {
	    proxy_pass http://localhost:9001;
	    proxy_http_version 1.1;
	    proxy_set_header Upgrade $http_upgrade;
	    proxy_set_header Connection 'upgrade';
	    proxy_set_header Host $host;
	    proxy_cache_bypass $http_upgrade;    
    }
    
    location /assets {
        # don't always know who ~is
        root  /usr/lib/node_modules/frontail/lib/web/;
    }
