### ISSUE TITLE
Need help for run custom or multiple logs

### ISSUE THREAD

**Issue by miteshwalker** [mthenw/frontail#74]
Hi,
I want to use your tool for my servers with docker, As I run the same with default conf, like with syslog it is working fine. But I want to run with my custom logs files. but with the same it is not working for me. Please find what  I am doing to see my nginx logs in web using docker.

docker run -d -v /var/log/nginx/access.log:/nginx-access -P mthenw/frontail /nginx-access
when I check with "docker ps -a"
I got exited 
Please help.

Thanks

**Comment by mthenw** [comment]
Hey,

what version of Docker do you use?
