### ISSUE TITLE
deprecated xss sanitizer in validator module

### ISSUE THREAD

**Issue by jupe** [mthenw/frontail#75]
Looks that latest version of [validator is no more xss sanitization](https://www.npmjs.com/package/validator#xss-sanitization) which are used [here](https://github.com/mthenw/frontail/blob/master/index.js#L124).

```
XSS sanitization was removed from the library in 2d5d6999.
```

Propose to change it to something which are not deprecated..

**Comment by mthenw** [comment]
Hey, 

thanks for reporting. Are you interested in fixing that?
