### ISSUE TITLE
Color support for newly appended lines

### ISSUE THREAD

**Issue by spacediver** [mthenw/frontail#77]
Hey, I have this upon loading frontail (3.0.0) page (looks okay): 

![Screenshot1](http://dl1.joxi.net/drive/2016/09/04/0017/2478/1169838/38/ca7a27a960.png)

And then, after posting more lines to both files, it looks not okay: 

![Screenshot2](http://dl2.joxi.net/drive/2016/09/04/0017/2478/1169838/38/d0b8048d3c.png)

**Comment by spacediver** [comment]
Actually, it is true even for a single file. Appended lines are not color-processed.

**Comment by mthenw** [comment]
@spacediver thanks for reporting! 

Fixed in 3.2.1. Docker image also updated.
