### ISSUE TITLE
re: v3.1.2

### ISSUE THREAD

**Issue by ORESoftware** [mthenw/frontail#78]
Hi good sir

Looks like your new version handles control chars better, and I thank you for that! The one thing remaining that I see is that it does not handle newline chars perfectly.

For example:

expected

![screenshot 2016-09-04 22 14 39](https://cloud.githubusercontent.com/assets/11139560/18237973/c8c75bf4-72ec-11e6-8c75-dea0a3f519d4.png)

actual

![screenshot 2016-09-04 22 13 20](https://cloud.githubusercontent.com/assets/11139560/18237975/cf74ac7c-72ec-11e6-8f5d-f74e2f0bab75.png)

this should be valid, let me know what you think! thx!

**Comment by mthenw** [comment]
Hmm, will take a look. Thanks!

**Comment by ORESoftware** [comment]
was there ein Fix?

**Comment by mthenw** [comment]
Version 4.0.1 fixes that.

**Comment by ORESoftware** [comment]
geil ist!
