### ISSUE TITLE
Error: spawn tail ENOENT on Windows 7 and Windows 8

### ISSUE THREAD

**Issue by danielpacak** [mthenw/frontail#81]
I got the following error on Windows 8 and Windows 7 with Node v4.4.5:

```
C:\>frontail okp.log
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn tail ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

However it works perfectly fine on Windows when I run the frontail through Git Bash. Is there something OS specific in the implementation that might cause the error?

**Comment by mthenw** [comment]
Hey @danielpacak, frontail requires `tail` command available in OS. It's not present in Windows. 

I guess that "Git Bash" is some kind of linux shell emulation, isn't it?

**Comment by danielpacak** [comment]
Ah, my bad. I thought that you're watching log files programmatically with the `fs` package, streams and stuff instead of spawning a child tail process. Indeed Git Bash provides a shell emulator with some useful linux commands including `tail`, hence it works. Anyways the error message speaks for itself.
