### ISSUE TITLE
It is possible to not view the message: "tail -F xxx"

### ISSUE THREAD

**Issue by jabrena** [mthenw/frontail#85]
Hi,

I am using frontail in a environment and I would like to know if exist a way to disable the message about: "tail -F xxxx"

Many thanks in advance.

Juan Antonio

**Comment by mthenw** [comment]
Do you mean hiding whole top bar (with a search field) or only text saying "tail -f ..."?

**Comment by jabrena** [comment]
Yes, when you handle several microservices, the title is large so it we could hide, it could be nice. It is responsability of the sys admin to load all log files.

**Comment by jabrena** [comment]
One alternative, could be show something like: "tail -F ..." with an anchor and past all details on a title attribute:
http://www.w3schools.com/tags/att_global_title.asp

**Comment by mthenw** [comment]
`title` attribute and `text-overflow: ellipsis;` I think is the best solution for that. Don't have enough time to fix that right now. @jabrena are you interested in contributing?

**Comment by jabrena** [comment]
Yes, mate

**Comment by jabrena** [comment]
Today, I found the HTML code to omit title:

```
<span class="navbar-brand" href="#">tail -F __TITLE__</span>
```

I will check how to send the variable Data in order to not inject in the web document.
