### ISSUE TITLE
Docker image does not like wildcards

### ISSUE THREAD

**Issue by msh100** [mthenw/frontail#88]
Always just returns file not found.

I believe the issue is that in a Docker container, the entrypoint is directly node which doesn't interpret the * and the node app doesn't handle globbing.

**Comment by msh100** [comment]
I believe the issue is that in a Docker container, the entrypoint is directly node which doesn't interpret the * and the node app doesn't handle globbing.

**Comment by mthenw** [comment]
Hey, thanks for reporting! I will look into it.
