### ISSUE TITLE
duplicate lines on auto-refresh

### ISSUE THREAD

**Issue by working-name** [mthenw/frontail#89]
Hello, is appending the same lines previously listed on page load the intended behavior?

**Comment by mthenw** [comment]
Hmm, I'm not sure what do you mean by auto-refresh? There is only one page load (when you open the website). Logs are sent from server via socket.io.

**Comment by working-name** [comment]
basically the log lines keep duplicating whether new lines are appended to the logfile being watched or not. Here's a screencast, words are failing me.
[screencast in mp4 format](https://bugout.regex.cf/this.mp4) 

Please keep in mind duplication happens on socket.io push, the video shows quite a few duplicates at the end, but that's across 5 minutes of recording.
