### ISSUE TITLE
Use frontail embedded my app source

### ISSUE THREAD

**Issue by rafaelquines** [mthenw/frontail#90]
Hi.
I'm developing an app in nodejs that basically monitor some raspberry pi inputs.
Actually I already use frontail in my app to monitor app logs.
But my app calls frontail by shell execute.

Is there some form I "require" frontail, and init it by my source, instead of call external?

Or I would need copy frontail source code and put inside my source app?

Can you help me?

Thanks

**Comment by mthenw** [comment]
Hey, no there is no to programmatically run frontail. The only way is run it from shell.
