### ISSUE TITLE
Unresponsive after back in focus

### ISSUE THREAD

**Issue by mefjush** [mthenw/frontail#93]
How to reproduce:
1. Lose the window focus
2. Push a large number of lines to the log file (1000?)
3. Focus the window again
4. The page is unresponsive for quite a while (not able to scroll, select/deselect lines, etc)
(Tested on Chrome 56.0.2924.87 on Mac OS)

It looks like Tinycon needs a lot of cpu time to execute setBubble (and it's invoked for each new line).

As a temporary bypass I've used this hack:

```
Tinycon.innerSetBubble = Tinycon.setBubble;
var faviconUpdateTimer = null;
var faviconN = 0;
Tinycon.setBubble = function(n) {
  faviconN = n;
  if (!faviconUpdateTimer) {
    faviconUpdateTimer = setTimeout(function() {
      faviconUpdateTimer = null;
      Tinycon.innerSetBubble(faviconN);
    }, 1000);
  }
};
```

**Comment by mthenw** [comment]
Thanks for info. I will looks into it.

**Comment by mthenw** [comment]
Hey,

I've just publish v4.0.2. Please check and let me know if this issue still occurs.

**Comment by mefjush** [comment]
Yup. That solves the problem. Thanks.
