### ISSUE TITLE
ability to tail output which is being redirected to stdout/stderr?

### ISSUE THREAD

**Issue by leonstafford** [mthenw/frontail#95]
I have a log file in a Docker container, which is symlinked to `/dev/stderr`. Have been tailing this with built-in `tail` command, now want to serve this using `frontail`. Other log files which are not symlinked are being served fine by `frontail`.

Do you know of a way I may be able to overcome this?

**Comment by mthenw** [comment]
As there is no support for files like `/dev/stderr` you can use frontail together with tail:

```
tail /dev/stderr | frontial -
```

**Comment by leonstafford** [comment]
Awesome, thanks!
