### ISSUE TITLE
Reverse proxy issues

### ISSUE THREAD

**Issue by amirabiri-odoro** [mthenw/frontail#97]
I could not figure out how to run frontail behind an nginx reverse proxy.

I've tried the following nginx configuration:

    location /logs/ {
        proxy_pass http://frontail/;
        sub_filter_once off;
        sub_filter_types text/html;
        sub_filter 'href="/' 'href="/logs/';
        sub_filter 'src="/' 'src="/logs/';
        sub_filter "io.connect('/'" "io.connect('/logs/'";
        access_log /var/log/nginx/access.log trace;
    }

The assets worked, but the socket.io still tries to connect to `/?E...`

Is it possible to add some cmd line switch to tell frontail which url path to use?

Or even better - use relative paths for assets / socket?

**Comment by scottbasgaard** [comment]
Any updates on this @amirabiri-odoro? Would love to have the same setup.

**Comment by amirabiri-odoro** [comment]
I resorted to running on root path on a different port.

**Comment by carschrotter** [comment]
> 
> 
> Any updates on this @amirabiri-odoro? Would love to have the same setup.
replace 
`sub_filter "io.connect('/'" "io.connect('/logs/'";` with 
`sub_filter "path: '/socket.io'" "path: '/logs/socket.io'";`
works fine

**Comment by scottbasgaard** [comment]
thanks @carschrotter, will give it a go!
