### ISSUE TITLE
Highlighting problems

### ISSUE THREAD

**Issue by sirLeone** [mthenw/frontail#99]
I think that there is some problem with highlighting. I have prepared my json script and its working only partially :)

`
{
    "words": {
        "[ERROR]": "color: red;",
        "[WARN ]": "color: yellow;",
        "[INFO ]": "color: white;"
    },
    "lines": {
        "[ERROR]": "font-weight: bold;",
        "[ItemStateChangedEvent     ]": "font-weight: bold;"
    }
}
`
Only WARN and INFO are working, unfortunatelly rest not :( Text/words were copied straight from frontline output so they should be correct.

![image](https://user-images.githubusercontent.com/16336937/28229725-2cc162e2-68e4-11e7-9043-fb37215b33c8.png)

**Comment by mthenw** [comment]
Hey, 

thanks for reporting. I'm not able to reproduce that. Can you paste exact log that it's not working?
